name: Pull request labeler
on: [pull_request_target, push]

# https://github.com/actions/labeler
# Pull Requestで変更されたファイル群のパスに基づいて、設定したラベルを自動付与するアクション
jobs:
  # 入力としてGitHubトークンを渡す
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # 必須
          configuration-path: .github/labeler.yml # ラベルの設定ファイルのパス
