name: hello world
author: mozumasu
description: "echo Hello world"
inputs:
  who-to-greet:
    description: "Who to greet 一人目(必須)"
    required: true
    default: "World"

  who-to-greet2:
    description: "二人目(任意)"
    required: false

outputs:
  greeting-world:
    description: "Greeting to someone"
    value: ${{ steps.hello.outputs.greeting-world }}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    WHO_TO_GREET: ${{ inputs.who-to-greet }}
    WHO_TO_GREET2: ${{ inputs.who-to-greet2 }}
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.who-to-greet2 }}
