name: hello world
author: mozumasu
description: "echo Hello world"
inputs:
  who-to-greet:
    description: "Who to greet 一人目(必須)"
    required: true
    default: "World"

  who-to-greet2:
    description: "二人目(任意)"
    required: false

outputs:
  greeting-world:
    description: "Greeting to someone"
    value: ${{ steps.set-output.outputs.greeting-world }}
runs:
  using: "composite"
  steps:
    # 渡されたinput
    - run: echo "渡されたinput ${{ inputs.who-to-greet }}"
      shell: bash
      # outputsの変数を変更
    - id: set-output
      run: echo "greeting-world=$(echo "Hello ${{input.who-to-greet}}") >> $GITHUB_OUTPUT
      shell: bash
    # 現在のディレクトリパスを取得して同ディレクトリ内のファイルを実行できるようにする
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    # # bashでgoodbye.shを実行
    # - run: goodbye.sh
    #   shell: bash
