# https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'mozumasu/github-actions-quick-start'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats

  # 三項演算子
  ternary-operator:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ github.ref == 'refs/heads/main' && 'value_for_main_branch' || 'value_for_other_branches' }}
    steps:
      - run: echo ${{ github.ref == 'refs/heads/main' && 'main' || 'other' }}
      - run: echo ${{ env.MY_ENV_VAR }}
