name: Pull request labeler
on: [pull_request_target]

# https://github.com/actions/labeler
jobs:
  # 入力としてGitHubトークンを渡す
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
