name: Manual Deploy
run-name: "${{ github.event.inputs.target }}: ${{github.event.inputs.message}}"

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: デプロイ先
        options:
          - develop
          - nightly
      message:
        description: デプロイ理由
        required: true
        default: "例: 機能追加のため"

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
      # デプロイ権限のチェック
      - name: check deploy permission
        if: github.actor_id != 93071448
        run: |
          echo "not have permission to deploy"
          exit 1

      # デプロイ先がdevelopの場合のみ実行
      - name: deploy to develop
        if: ${{ github.event.inputs.target }} == 'develop'
        run: |
          echo "deploy to develop"
          echo ${{ github.event.inputs.target }}

        # デプロイ先がnightlyの場合のみ実行
      - name: deploy to nightly
        if: ${{ github.event.inputs.target }} == 'nightly'
        run: |
          echo "deploy to nightly"
          echo ${{ github.event.inputs.target }}
