name: 【Test】Add Tag
on: workflow_dispatch

# GitHub Tag - GitHub Marketplace
# https://github.com/marketplace/actions/github-tag

# 参照
# https://dev.classmethod.jp/articles/howto-use-github-tag/
jobs:
  add-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # major.minor.patchのいずれかをインクリメントする
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 必須
          default_bump: "minor"
          # キーワードによるインクリメントは、含まれる中で一番大きなものが1つ加算される(major > minor > patch)
          # patchキーワード　fix: XXXXX
          # minorキーワード　feat: XXXXX
          # majorキーワード　BREAKING CHANGE: XXXXX または perf: XXXXX
          # それ以外の場合はdefault_bumpで指定したバージョンをインクリメントする

      # リリースノートを作成する
      - name: Publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
