name: 【Test】ワークフロー内の環境変数のテスト
run-name: 【Test】ワークフロー内の環境変数のテスト

on:
  workflow_dispatch:
    inputs:
      test:
        description: "テスト"
        required: true
        default: "テスト"

env:
  WORKFLOW_ENV: ワークフロー内の環境変数だよ

jobs:
  check-env:
    runs-on: ubuntu-latest
    env:
      ENV_JOBS: ジョブ内の環境変数だよ
    steps:
      - name: ワークフロー内の環境変数のテスト
        run: |
          echo env.WORKFLOW_ENV: ${{ env.WORKFLOW_ENV }}

      - name: JOB内の環境変数のテスト
        run: |
          echo env.ENV_JOBS: ${{ env.ENV_JOBS }}

      - name: アクション内の環境変数のテスト
        env:
          ENV_ACTIONS: アクション内の環境変数だよ
        run: |
          echo env.ENV_ACTIONS: ${{ env.ENV_ACTIONS }}

  check-workflow-env:
    runs-on: ubuntu-latest
    steps:
      - name: ワークフロー内の環境変数のテスト
        run: |
          echo env.WORKFLOW_ENV: ${{ env.WORKFLOW_ENV }}

      - name: JOB内の環境変数のテスト
        run: |
          echo env.ENV_JOBS: ${{ env.ENV_JOBS }}

      - name: アクション内の環境変数のテスト
        run: |
          echo env.ENV_ACTIONS: ${{ env.ENV_ACTIONS }}
