name: 【Test】スクリプトの呼出し
on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: chage permission
        run: chmod +x ./test.sh
      - name: Run a script
        run: ./scripts/test.sh
