name: 【Test】Share Artifact
on: workflow_dispatch

# artifact: ジョブの実行結果を保存するための機能
# https://docs.github.com/ja/actions/learn-github-actions/essential-features-of-github-actions
jobs:
  apload-artifact:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo $((1 + 1)) > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log

  download-artifact:
    needs: apload-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
      - name: cat output.log
        run: cat output.log
