name: 【Test】ワークフロー内の環境変数のテスト
run-name: 【Test】ワークフロー内の環境変数のテスト

on: workflow_dispatch
env:
  WORKFLOW_ENV: ワークフロー内の環境変数

jobs:
  check-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: ジョブ内の環境変数
    steps:
      - name: ワークフロー内の環境変数のテスト
        run: |
          echo env.WORKFLOW_ENV: ${{ env.WORKFLOW_ENV }}

      - name: JOB内の環境変数のテスト
        run: |
          echo env.JOB_ENV: ${{ env.JOB_ENV}}

      - name: アクション内の環境変数のテスト
        env:
          ACTION_ENV: アクション内の環境変数
        run: |
          echo env.ACTION_ENV: ${{ env.ACTION_ENV}}

  check-workflow-env:
    runs-on: ubuntu-latest
    steps:
      - name: ワークフロー内の環境変数のテスト
        run: |
          echo env.WORKFLOW_ENV: ${{ env.WORKFLOW_ENV }}

      - name: JOB内の環境変数のテスト
        run: |
          echo env.ENV_JOBS: ${{ env.ENV_JOBS }}

      - name: アクション内の環境変数のテスト
        run: |
          echo env.ENV_ACTIONS: ${{ env.ENV_ACTIONS }}
