on: push

name: Hello world
run-name: ${{github.ref}} Hello world
jobs:
  call_helllo_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world
        with:
          who-to-greet: "mozumasu"
