name: 【Test】action.ymlの呼出し
on: workflow_dispatch

run-name: 【${{github.ref}}】 action.ymlの呼出し
jobs:
  call_helllo_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: hello
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: "mozumasu"
      - run: echo "The greeting was ${{ steps.hello.outputs.greeting-world}}"
        shell: bash
