name: 【Test】Job間の変数の受け渡し
on: workflow_dispatch

# https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
# JOB間の変数の受け渡しには$GITHUB_OUTPUTを使用する
# Step間の変数の受け渡しには$GITHUB_ENVを使用する

# JOB間の変数の受け渡し
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

  # 練習
  job3:
    runs-on: ubuntu-latest
    outputs:
      # stepのidが無いとエラーになる
      #   output1: ${{ steps.outputs.test2 }}
      #   output2: ${{ steps.outputs.test2 }}
      output1: ${{ steps.step1.outputs.test2 }}
      output2: ${{ steps.step2.outputs.test2 }}
    steps:
      # GITHUB_OUTPUTを使用する時は、stepのidが必要
      - id: step1
        run: echo "test2=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test2=world" >> "$GITHUB_OUTPUT"

  job4:
    runs-on: ubuntu-latest
    # needs必須
    needs: job3
    steps:
      - env:
          OUTPUT1: ${{needs.job3.outputs.output1}}
          OUTPUT2: ${{needs.job3.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
